trusted_cert: "../assets/client/cacert.pem"
server_addr: "lunnel.snakeoil.com:8080"
tunnels: 
  2048: 
    proto: "http"
    local: "http://lunnel.snakeoil.com:32768" 
  docker: 
    proto: "http"
    local: "unix:///var/run/docker.sock"
  2048_2: 
    proto: "tcp"
    local: "http://lunnel.snakeoil.com:32768" 
encrypt_mode: "aes"

