trusted_cert: "../assets/client/cacert.pem"
server_addr: "10.1.4.157:8080"
tunnels: 
  2048: 
    proto: "http"
    local: "http://10.1.4.58:32768" 
  docker: 
    proto: "http"
    local: "unix:///var/run/docker.sock"
  2048_2: 
    proto: "tcp"
    local: "http://10.1.4.58:32768" 
encrypt_mode: "none"

